### ISSUE TITLE
Zero values for heading

### ISSUE THREAD

**Issue by Ahleroy** [SBG-Systems/sbg_ros_driver#73]
I am currently using an Ellipse D system that works fine for every ROS topic expect the /sbg/gps_hdt one.
The ros_topic exists and is listened without issue, however the output values are always zeros.

This is an output example of the ROS topic /sbg/gps_hdt : 

```
header:
  seq: 137
  stamp:
    secs: 1636727118
    nsecs: 870406178
  frame_id: "imu_link_ned"
time_stamp: 2170420000
status: 1
tow: 483935600
true_heading: 0.0
true_heading_acc: 0.0
pitch: 0.0
pitch_acc: 0.0
```
Any idea why the outputs (true_heading, true_heading_accuracy, pitch, pitch_accuracy) are always zeros ?
